services:
  # MongoDB
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: future_blink
    volumes:
      - mongodb_data:/data/db

  # Redis Stack
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack-future-blink
    ports:
      - "6379:6379"
      - "8001:8001"

volumes:
  mongodb_data:
